    dim: 64              # dimension of embedding vector
    depth: 6             # depth of transformer
    heads: 4             # number of heads in transformer
    mlp_dim: 256         # Karpathy's mlp_dim is 4*dim
    dim_head: 16         # dimension of head
    no_attn_feedthrough: False