num_layers: 2
num_refinement_blocks: 2
refinement_bottleneck: 2
skip_connections: false
skip_dropout_p: 0

disable_norm: false
with_downsampling: true
with_learned_pooling: false
keep_dim_during_up_conv: false
refinement_blocks: "simple"
    