num_layers: 2
refinement_layers: 2
refinement_bottleneck: 2
skip_connections: true
skip_dropout_p: 0
loss_layer_weights: [] #[0.25, 0.5, 0.75]

disable_batchnorm: false
with_downsampling: true
with_learned_pooling: false
refinement_blocks: "simple"
    